### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by bstiq**

### CODE REVIEW

**Comment by bstiq** [comment]
@casuanoob 

Thanks for your work, excellent routing.
Can't vouch for the jumpers as I'm not super familiar as to how custom matrix works.

General notes:
- update 1.0 on silkscreen to eg. 1.1

On the LEDs:
Which side do you want them to shine ? Per the footprints at the moment, they will shine to the bottom (towards the desk / opposite of the rotary encoder).
Double check as I'm always making mistakes with LEDs.
If you want them to shine towards the other side (top/towards rotary encoder), you will need to flip Vdd/Dout and Din/Gnd.

See picture:
image
image

Notice that on the thumb cluster pcb, the pads are inverted on each side.
If this is the wanted behaviour, please ignore.

Cheers

**Comment by casuanoob** [comment]
@bstiq thanks for the catch, I've flipped the LEDs and I think they're correct this time around.

I've also reverted the 6 pin connector pinout to retain compatibility with the original pinout for my own sanity - R1 and R2 are swapped but this should only invert the rotation direction as they're connected to encoder pads A and B.

The Row and extra DIN pin headers have been removed as both of these were duplicating existing pins for no real reason. 
This simplifies the configuration process to setting one solder jumper instead of two.

**Comment by bstiq** [comment]
LGTM ! Let's order it and merge this as soon as it's tested. I have to make an order soon (in the coming few weeks) so I'll probably add this one as well

**Comment by bstiq** [comment]
[1.1.2.zip](https://github.com/Bastardkb/Charybdis-EC11/files/8603004/1.1.2.zip)

Gerber for 1.1.2

Ordering soon

**Pull request merged**
