### PR TITLE
Adjusted bottom mount. Added knobs.

### PR DESCRIPTION
**Pull request by AlexBaldwin42**
I don't know why the knob is tilting in the original file but this bottom straightens it. 
Also added two knobs the large one does NOT work on the Charybdis.

### CODE REVIEW

**Comment by bstiq** [comment]
Thank you ! Why did you add the large one if it doesn't work on the Charybdis ? Does it work on the nano ?

**Comment by AlexBaldwin42** [comment]
It only works on my 3x5_3 models. I could decrease the size of it enough to fit if there is interest. I removed the large knob in my latest commit. I would recommend testing the new bottom to make sure the adjustment works.

**Comment by bstiq** [comment]
Hi,

Thanks. I will print and test the new bottom in the coming days.

**Comment by bstiq** [comment]
Just tested, it works. Thanks !

**Pull request merged**
